### ISSUE TITLE
Missing sampleGraph

### ISSUE THREAD

**Issue by dacohen** [gtagency/graph-reduction#5]
You probably forgot to include it when you pushed your commit.

**Comment by irapha** [comment]
I think I purposely deleted it. I am pretty sure sample graph is now matrix26 in the tests.py file. If you want to use sampleGraph, just uncomment the matrix = matrix26 line and comment out all other assignment lines.

**Comment by dacohen** [comment]
However, its required by the randomPermutations module. What's the fix?

**Comment by irapha** [comment]
So, my initial idea is to remove that dependency. There isn't (or there shouldn't be) a situation in which we would call randomPermutation without providing it a matrix. I could do that, unless you think we'd ever call randomPerm without parsing in a matrix

**Comment by dacohen** [comment]
I think either is fine, whichever is easier. The issue is that the code does not run as is.

**Comment by irapha** [comment]
Oh, you might have a different version of python because it runs fine on my computer. Either way, fixed.
