### ISSUE TITLE
Overlapping points makes it very hard to get rid of intersections

### ISSUE THREAD

**Issue by irapha** [gtagency/graph-reduction#7]
With matrixStar, overlapping points (specifically overlapping point/edges) is making it very costly for the annealing to move vertices into an area inside from edges. This means that the end result has a lot of intersections. Just try running the code with matrixStar having overlappingPoints' weight be 0.5, then try it with weight 0.

**Comment by robert-lawrence** [comment]
alright, I have an idea that might work.
We pass in the temp (or the time) to the score fn and have it only weight overlap heavily towards the end to the annealing process. That way there's lots of time for the other scores to remove intersections, then towards the end the code will allow the overlap fn to correct any overlap

**Comment by irapha** [comment]
Sounds like a good idea. I don't know if there could be any edge cases in which that wouldn't work, but I can't think of any so I'll say let's try that

—
